### ISSUE TITLE
Output from stderr pollutes the screen

### ISSUE THREAD

**Issue by lgbaldoni** [Dudemanguy911/vmn#3]
Unsure whether this is something that ought to be addressed by the terminal, but I see things like
`libEGL warning: DRI2: failed to authenticate`
and
`Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory`

that mess up the song list.

**Comment by Dudemanguy** [comment]
Yeah this issue is known. Basically any mysterious driver error gets propagated from the mpv backend to the curses window. As far as I know, there's not a simple "don't print stdout/stderr" function in ncurses so dealing with this is tricky. There may be some way to mess with your terminal settings to prevent this, but I'm not aware of it.

This one bothers me too because on one of my machines I get some nonsensical mesa message that as far as I know does nothing. I guess I could bruteforce an entire menu refresh anytime mpv is initialized but that's an ugly workaround imo and also introduces other problems.

**Comment by Dudemanguy** [comment]
It turns out that a simple trick with `freopen` solves this (see fa91b787). If I ever get around to making error handling more sophisticated, `/dev/null/` can be changed to something else as well.
